### PR TITLE
Sort and filter

### PR DESCRIPTION
**Pull request by danielfdsilva**
This PR adds a table comoponent which allow to easily set filters and sorts on the headers.
Check the `admin-area.js` file to see how it's implemented.

TODO on the `admin-area.js`
- [x] Compute filters
- [x] Verify api connection

TODO overall;
- [x] Replace tables with Component. There are some pages where this table structure is not being used, like the homepage. Changing it should be pretty fast.

Any question just reach out

cc @derek

### CODE REVIEW

**Comment by danielfdsilva** [comment]
@dereklieu I'd say that overall this is ready. Just 2 things missing:

- [ ] Appeals, DREFs and Field Reports are not filterable by dtype
- [ ] Alerts table not filterable by date

There may be missing headers to sort / filter. We should do a general check.

**Comment by danielfdsilva** [comment]
@dereklieu @ascalamogna Reviewed the sort/filter according to #58.

**Emergencies**
date - dropdown
> For the date we're displaying `disaster_start_date` or `start_date` or `created_at` depending on what is available. @dereklieu How do you propose we implement a filter here?

Disaster Type - dropdown
> @dereklieu is checking feasibility of filtering by a relation

total affected - sort
> This is not present on the table

total beneficiaries - sort
> This is a sum of the beneficiaries of each appeal. @dereklieu can this be sorted?

**Field Reports**
disaster type- dropdown
> @dereklieu is checking feasibility of filtering by a relation

region - dropdown
> This is not present on the table

**Appeals/Drefs**
disaster type -dropdown
> @dereklieu is checking feasibility of filtering by a relation

**HeOps**
> I used the implemented structure as guide for what to sort/filter on.

**Comment by dereklieu** [comment]
@danielfdsilva @ascalamogna it turns out that you can directly order by related fields such as `country` or `dtype` and it works as expected. Aggregated fields, such as `total_beneficiaries` for the emergencies page, which is calculated from all the associated appeals, cannot be ordered on, and neither can many-to-many fields such as `regions` and `countries.`

**Comment by dereklieu** [comment]
@danielfdsilva also for the emergencies date, I propose we use `disaster_start_date`.

**Pull request merged**
