### PR TITLE
Release/v4.3.9

### PR DESCRIPTION
**Pull request by batpad**
### Release 4.3.9

Frontend:

 - 3w: Make fields not required if reporting society is ICRC: https://github.com/IFRCGo/go-frontend/issues/1334
 - 3w: Project completed changes budget field to actual expenditure: https://github.com/IFRCGo/go-frontend/issues/1319
 - Fix display of country, region in field report listing on Emergency pages: https://github.com/IFRCGo/go-frontend/issues/1122
 - Fix redirect of Add Report button to go to Emergency page in Admin: https://github.com/IFRCGo/go-frontend/issues/1116

Backend:

 - Remove status=completed and reached_total is defined validation from 3W (This is handled on the frontend now) - https://github.com/IFRCGo/go-api/pull/792/files#diff-181356e13945b05b6ffefda13468c403L134-L136
 - Added the previous email sending method back (python's smtplib) as a backup if sending emails with the API fails - https://github.com/IFRCGo/go-api/issues/737
 - Fix some of the logs failing because of missing recordtypes
 - Retaining Django (cronjob) logs with a new volume added to the docker container - MSM ticket

Checklist:
 - [ ] Tag and push version on frontend
 - [ ] Deploy backend
 - [ ] Deploy frontend
 - [ ] Verify logfile persistence on backend
 - [ ] Merge master -> develop on frontend
 - [ ] Move tickets to `Done`.

### CODE REVIEW

**Comment by GregoryHorvath** [comment]
I can't say much about the CHANGELOG but I'd suggest we pull this out of the release: a17c647 (merge PR 1b91263)

**Comment by frozenhelium** [comment]
:+1:  @batpad the CHANGELOG looks good, those 2 3W tasks are only the changes from my side

**Comment by thenav56** [comment]
@frozenhelium @batpad The changelog for backend from my side

Remove `status=completed and reached_total is defined` validation from 3W (This is handled from the go-frontend now). https://github.com/IFRCGo/go-api/pull/792/files#diff-181356e13945b05b6ffefda13468c403L134-L136

**Comment by batpad** [comment]
> Remove status=completed and reached_total is defined validation from 3W (This is handled from the go-frontend now). https://github.com/IFRCGo/go-api/pull/792/files#diff-181356e13945b05b6ffefda13468c403L134-L136

Thanks @thenav56 - added to the CHANGELOG. @GregoryHorvath whenever you're able, can you please add your changes?

**Comment by GregoryHorvath** [comment]
> Thanks @thenav56 - added to the CHANGELOG. @GregoryHorvath whenever you're able, can you please add your changes?

@batpad Sorry I always forget this changelog is for both the backend and the frontend. Updated, and removed the part which would affect the Rich Text Editors.

**Comment by batpad** [comment]
@LukeCaley have updated the PR comment above with the release notes and deploy checklist.

cc @frozenhelium @GregoryHorvath @thenav56 @nanometrenat

**Pull request merged**
