### PR TITLE
Fix/1189 validation

### PR DESCRIPTION
**Pull request by necoline**
## Issue
#1189 

## Description
This adds additional validation to start date and changes numbers to integers

I also fixed an issue I encountered where I couldn't clear the country dropdown because `updateDistricts` was expecting a value from countries

This resolves everything on the ticket with the exception of the date validation. See issue for further conversation.

### Testing Instructions
https://ifrc-go-fix-1189-validation.surge.sh/reports/new

should error on:
- adding an invalid start date
- adding a number in step 2 (or others) with decimal 

should pass on:
- adding a valid start date
- adding a country, clearing the country and adding again
- adding an integer for fields in step 2 (or others)

### CODE REVIEW

**Comment by batpad** [comment]
@necoline this looks good to me!

My suggestion for right now would be that validating that something "is a date" is good enough. I'd be wary of enforcing before / after validations in the dates as I know there likely can be various edge cases where people may want to enter dates in the past / future.

@necoline can we publish this to a surge URL for testing? Instructions in the README / happy to chat about it.

Thanks so much! This is looking great.

**Comment by necoline** [comment]
I don't know how I forgot about my favorite addition to the testing process 🤦 .
https://ifrc-go-fix-1189-validation.surge.sh/reports/new

**Comment by batpad** [comment]
@karitotp could you please test this above URL for the validation fixes and leave comments on https://github.com/IFRCGo/go-frontend/issues/1189 ? thanks!

**Comment by necoline** [comment]
@batpad Karito found an issue with the error messages on the epi-source inputs which I fixed above. 

I think it's ready for a final review

**Pull request merged**
