### PR TITLE
[WIP] Improve homepage charts

### PR DESCRIPTION
**Pull request by danielfdsilva**
@ascalamogna A lot more information was added to the tooltip. It may be worth to revisit the style and structure of it.
Leaving this as a WIP until you get a chance to look it over.

### CODE REVIEW

**Comment by ascalamogna** [comment]
@danielfdsilva I styled the tooltip but there are some issues with the placement of the tooltip. I'm not sure if this is because I broke it into two columns or not. Let me know and I can figure out a different solution if this won't work.

**Comment by danielfdsilva** [comment]
@ascalamogna What sort of issues are you referring to?

**Comment by ascalamogna** [comment]
@danielfdsilva if you hover on a spot and then move your mouse around, the line disappears under the popover.

**Comment by danielfdsilva** [comment]
@ascalamogna The popup renders inside the chart area and has a lot of information. It has nowhere to go. I don't know how we can solve this. Would adding some transparency to the tooltip help? You'd be able to see it behind. Any ideas?

**Comment by ascalamogna** [comment]
@danielfdsilva I see what you're saying. I added some transparency and I think that works best for now. thanks!

**Comment by danielfdsilva** [comment]
@ascalamogna Is this ready to go?

**Pull request merged**
