### PR TITLE
Update Surge page map with ERUs and Personnel data

### PR DESCRIPTION
**Pull request by willemarcel**
Contributes to #1965

### CODE REVIEW

**Comment by willemarcel** [comment]
> Hi @willemarcel, @batpad. Looks good, but I think, the colors need to be aligned with those on the active operations map:
> #ff9e00
> #4c5d9b
> Thanks!

@tovari I pushed an update with the new map colours and deployed it: https://upbeat-bartik-c5abb7.netlify.app/deployments

**Comment by tovari** [comment]
Hi @willemarcel, I think the displayed ERUs on the map are filtered by the ERU list pages, i.e. only those are visible that are on the actual page of the list. I could not check this for deployments as there is only 1 page at the moment. 
Check USA on the screenshots.
Further issue is that there is no mixed item is displayed on the map (USA should be).
Also, when clicking on page 3, the page breaks.
surge-map-1b

surge-map-2

**Comment by willemarcel** [comment]
Thanks for reporting the bugs, @tovari. I have already fixed them. You can check on the same URL.

**Comment by batpad** [comment]
Thanks @willemarcel - am going to go ahead and merge this to develop - we can make any additional fixes as separate branches.

**Pull request merged**
