### PR TITLE
Remove border-bottom from Lang. Select style

### PR DESCRIPTION
**Pull request by GregoryHorvath**
Aligns the Language dropdown with the other elements of that line.

### CODE REVIEW

**Comment by batpad** [comment]
@imohkay do you mind taking a quick look and reviewing?

@GregoryHorvath can we remove that line of code instead of commenting out?

**Comment by GregoryHorvath** [comment]
@batpad Sure, should I also create a surge url?

**Comment by batpad** [comment]
> @batpad Sure, should I also create a surge url?

Na, this seems small enough to just be tested in staging. Just want to get @imohkay's blessings for CSS changes.

**Comment by imohkay** [comment]
@batpad This looks good to me.

**Review by batpad — APPROVED** [review]

**Pull request merged**
