### PR TITLE
Feature/react bread crumb

### PR DESCRIPTION
**Pull request by necoline**
#770

This model utilized declarative communications through react tree with React Through to create the breadcrumbs. 
The crumb list is passed through props so that we can control which crumbs are associated with each page.

image

Design Mock: https://projects.invisionapp.com/share/K8R901UBXN4#/screens/360977415

Changes on 4/29
Updates
- adds country to emergency page - did not add region. I need to find a way to get region id using country id
- adds emergencies to field report, did not add emergency -- need to find a way to conditionally add a breadcrumb since not all field reports are linked to emergencies

Additions:
- PER forms
- Login
- Register
- Tables

## Deployed on staging: 
`old neco deploy: https://ifrc-go-feature-react-bread-crumb.surge.sh/`
new kamicut deploy: https://kamicut-ifrc-go-feature-react-bread-crumb.surge.sh/

### CODE REVIEW

**Comment by batpad** [comment]
@necoline sorry for the late review here --

This is looking really good to me so far - clicking through Emergency pages shows the breadcrumbs as expected.

The design / styles for the breadcrumbs should be available in zeplin.io - let me know if you need to be setup with access.

Also let me know if there's any work you wish to delegate / would like support on with implementing across all pages.

Also, when things are in a state that can be previewed / tested, would be great to push out a surge.sh url with this branch. I can walk you through that when we next talk.

I am :+1: on moving ahead with this approach. I'm going to close my other PR relating to breadcrumbs. Ty!

**Comment by necoline** [comment]
Awesome. I'll finish this up today and submit a real PR

**Comment by necoline** [comment]
I have access to the wireframes, so no worries there

**Comment by batpad** [comment]
@necoline this is looking really good to me!

Could you deploy this to a testing surge URL?

To do this you would need to:

 - Rebase / merge develop
 - Deploy to `surge` with `yarn build-staging && yarn deploy-surge`
 - You may need to login or create `surge.sh` credentials - you will be prompted
 - You should get back a URL with the deployment on surge.

**Comment by batpad** [comment]
Thanks @necoline for updating the test URL

@nanometrenat @teklal @yellowumbrella-design (for design input) - breadcrumb navigation can be tested at https://ifrc-go-feature-react-bread-crumb.surge.sh/

This refers to https://github.com/IFRCGo/go-frontend/issues/770 . Would appreciate any feedback / comments either here or in the linked ticket.

**Comment by batpad** [comment]
@yellowumbrella-design the screenshot above should indicate what it looks like without the grey overlay on staging. Please let us know any feedback on the look - I believe @necoline used the styles fro Zeplin, but would be better able to comment if there were any implementation details that meant things needed to be done differently or anything.

**Comment by necoline** [comment]
I'm moving the conversation from team to this issue since this will be the easiest place to pursue solutions. 

#770 Outlines the changes in this PR
#928 Discusses `Practical Navigation` and highlights ways that the breadcrumbs could be improved on

We have mockups:
https://projects.invisionapp.com/share/K8R901UBXN4#/screens/360977415
@yellowumbrella-design  are there other designs relating to this issue?

From an implementation standpoint it is worth noting that the breadcrumbs are written in a declarative manner meaning that we have the flexibility to determine which crumbs will appear on each page (rather than depicted the trail of pages the user navigated through to get to that page)

This means that it will not be difficult to change the crumbs to reflect the exact list of links that we want. 
However, we need a clear list of what that looks like for each page

@nanometrenat is it possible to 
- [ ] list all the pages that require breadcrumbs
- [ ] list breadcrumbs for each page

**Comment by necoline** [comment]
_please edit to add to or change the list_

- About
  - [x] home > about
- Account
  - [x] home > account
- Country
  - [x] home > region > country
- Deployment
  - [x] home > deployments
- Emergencies
  - [x] home > emergencies
- Emergency
  -  [ ] home > emergencies > region > country > emergency
- Field Report
  - [x] home > reports(account/notifications) > field report
- PER Forms
  - [x] home > account > PER form
- Preparedness
  - [x] home > preparedness
- Region
  - [x] home > region
- Tables(view all ...)
  - [x] home > name of table

**Comment by yellowumbrella-design** [comment]
@necoline The wireframes are accurate, but for UI, it's best to check Zeplin. Here is a screenshot of the breadcrumps design recommendation. The specs are in Zeplin as well. Happy to provide more info:
Screen Shot 2020-03-25 at 9 25 52 PM

**Comment by karitotp** [comment]
Result from frontend QA test:

- All of the main pages have breadcrumbs listed above

  Could not find: 
  - Field Report: home > reports(account/notifications) > field report
  - PER Forms: home > account > PER form
  - Tables(view all ...): home > name of table

- The styles match the designs on all pages
 
  Need changes to match with the mockups:
https://projects.invisionapp.com/share/K8R901UBXN4#/screens/360977415







- Links are all valid

  - This looks good.

**Comment by necoline** [comment]
Thanks @karitotp 

I had the same confusion on the styles. The preferred style is this 👇 
image

**Comment by kamicut** [comment]
I've merged develop into this, and it's ready to be reviewed! 

You can check my preview here https://kamicut-ifrc-go-feature-react-bread-crumb.surge.sh/

**Comment by batpad** [comment]
This is looking great to me! Thanks @kamicut . Am going to move the ticket over back to Ready for QA to get any final comments from them.

**Comment by batpad** [comment]
Have updated this PR with fixes for issues that @karitotp found in #770 :

 - Added breadcrumb for About / Resources page
 - Fixed inconsistent ordering of breadcrumbs due to default ordering being by URL length

Have updated at a new surge URL: https://batpad-ifrc-go-test-breadcrumbs.surge.sh/

I am slightly concerned with a crash I saw when navigating to a country page, but was unable to reproduce. If that doesn't seem to be an issue in QA, I think this should be good to merge to staging.

**Comment by nanometrenat** [comment]
Thanks @batpad - I had a reproducible crash at https://kamicut-ifrc-go-feature-react-bread-crumb.surge.sh/countries/282#operations (as mentioned in my comment at https://github.com/IFRCGo/go-frontend/issues/770#issuecomment-642089602), if that helps

**Pull request merged**
