### PR TITLE
Change sass deprication warnings

### PR DESCRIPTION
**Pull request by frozenhelium**

### CODE REVIEW

**Review by szabozoltan69 — APPROVED** [review]
What a great and  much appreciated fix! Many thanks for it!!!

**Comment by frozenhelium** [comment]
@szabozoltan69 should I go ahead and merge it?

**Comment by szabozoltan69** [comment]
Yes, you can, @frozenhelium 
There are still 2 warnings, but I think they concern to 3rd party library and not easy to fix on our side.
$gutter / $width * 100
($pxval / $base) * 1em

**Comment by frozenhelium** [comment]
@szabozoltan69 Yep, they can't be fixed at the moment. Maybe updating those libraries might fix it later.

**Pull request merged**
