### PR TITLE
Hotfix ops update export

### PR DESCRIPTION
**Pull request by frozenhelium**

### CODE REVIEW

**Comment by frozenhelium** [comment]
@szabozoltan69 Let's send this to prod. Thanks in advance :)

**Review by szabozoltan69 — APPROVED** [review]

**Comment by szabozoltan69** [comment]
@frozenhelium Deployment to Prod is in progress.
Can I merge master to develop? Or shall we cherry-pick some commits (from master) to develop?

**Comment by frozenhelium** [comment]
@frozenhelium We probably need to cherry-pick as there are some features hidden in the prod which we have to make visible again (if me merge)

**Comment by szabozoltan69** [comment]
Thanks @frozenhelium – I think it's better if you make that cherry-pick, as I am not so much in the picture.

**Comment by frozenhelium** [comment]
Sure, will do!

**Comment by frozenhelium** [comment]
@szabozoltan69 done! cherry-picked the changes to develop!

**Comment by szabozoltan69** [comment]
Deployed to Prod.

**Comment by szabozoltan69** [comment]
I begin the deployment the develop (to Staging).

**Pull request merged**
