### PR TITLE
Release v4.3.11

### PR DESCRIPTION
**Pull request by batpad**
### Release 4.3.11

This release includes a lot of code changes to support future translations support, as well as significant changes toward implementing updated site designs.

Frontend:

 - Replace all strings on the frontend with translatable strings: https://github.com/IFRCGo/go-frontend/issues/1239
 - Use new grid framework for styling, to support RTL languages: https://github.com/IFRCGo/go-frontend/issues/1382
 - Update styles across the site to match new designs:
   - UI Elements Update: https://github.com/IFRCGo/go-frontend/issues/1325
   - Update Key Figures Styling: https://github.com/IFRCGo/go-frontend/issues/1324
   - Table styling across platform: https://github.com/IFRCGo/go-frontend/issues/1203
   - Styling cleanup of Highlighted Operations + Adding Follow buttons: https://github.com/IFRCGo/go-frontend/issues/1206
 - Improvements to Signup Workflow: https://github.com/IFRCGo/go-frontend/issues/1233
 - Fix Create a Report dropdown on mobile: https://github.com/IFRCGo/go-frontend/issues/1363
 - Rename Subscribe / Unsubscribe to Follow / Unfollow on Emergency page: https://github.com/IFRCGo/go-frontend/issues/1370

Backend:

 - Update Docker base image for deploy, to support future Geospatial work: https://github.com/IFRCGo/go-api/pull/807
 - Optimize queries / improve performance of Events API endpoint: https://github.com/IFRCGo/go-api/issues/763
 - Optimize queries / improve performance of Appeals endpoint: https://github.com/IFRCGo/go-api/pull/828
 - Fix typo in cronjob: https://github.com/IFRCGo/go-api/issues/826
 - Add User Profile to User Admin page: https://github.com/IFRCGo/go-frontend/issues/956#issuecomment-659182089

### Deploy check-list

 - [x] Deploy backend @GregoryHorvath 
 - [x] Check backend deploy
 - [ ] Merge frontend to master
 - [ ] Tag and publish frontend new tag
 - [ ] Merge frontend master to develop

### CODE REVIEW

**Comment by batpad** [comment]
The release branch can be tested at https://ifrc-go-release-v4-3-11.surge.sh/ .

@frozenhelium @geohacker @imohkay @GregoryHorvath -- we can continue now merging things into develop to deploy to staging and have in the main branch, and use this release branch only for commits that need to make it to the 4.3.11 release (hopefully there will be very few, if any).

IF we make any changes to this release branch, they should be immediately brought into develop as well. Of course, we should not pull any changes from develop into here.

@imohkay - if we need to make fixes for the current release, please branch off from this branch (`release/v4.3.11`) and make PRs against this branch and not develop. For things that are going into future releases, branch off `develop` as normal.

**Comment by nanometrenat** [comment]
@batpad #956 was partly about adding User Profile to Users screen but actually the most important part was the addition of the Last frontend login field to the User Profile.  Is that going out in this release (back end or front end)?

**Comment by GregoryHorvath** [comment]
@nanometrenat Yes it does.

> Backend:
>
> - ...
> - Add User Profile to User Admin page: #956 (comment)

**Comment by karitotp** [comment]
@batpad, I did a quick review of all the pages and overall everything is good to me!

Some differences in the key numbers style with the design in zeplin:

Style in the emergencies page
Screenshot from 2020-08-07 09-58-04

Style in the design in zeplin
Screenshot from 2020-08-07 09-57-52

**Comment by nanometrenat** [comment]
@karitotp Thank you for double-checking!  I think your screenshots are reversed - Prod (and Staging/Surge) have "Emergencies | Affected People | Requested Amount (CHF) | Funding (CHF)" - which is great, as we haven't yet made the wording+figure calculation changes (only styling).

Agreed that this is diff to Zeplin (if the first shot is Zeplin)
This is Prod pre-release:
image

And this is surge URL pre-release:
image

**Comment by imohkay** [comment]
@nanometrenat If Mariam is okay with the general styling, are we good on key numbers looking somewhat different since their content is different on the site and Zeplin?

**Comment by nanometrenat** [comment]
@LukeCaley has confirmed that this specific release can go ahead as-is (in fact it has just been released to Prod now.

Separate ticket to be raised if/when it is decided to change what the Key Figures are in future (this is would not just be a cosmetic/styling change but also a calculation change

**Comment by imohkay** [comment]
Great @nanometrenat Thanks for updating :)

**Pull request merged**
