### PR TITLE
Release v4.4.0 - Safari

### PR DESCRIPTION
**Pull request by batpad**
### Release 4.4.0 - Safar(i)

_Safar_ / _Safari_ : A journey / expedition.

Release 4.4.0, codename `Safari`, has been a journey across languages, cultures and continents. Major updates in this release include translations of the platform into the 4 official languages of the IFRC. The release also includes a major overhaul of our handling of geo data, making spatial data a core part of the GO API.

### Frontend

 - Validation fixes on Field Report form: https://github.com/IFRCGo/go-frontend/issues/1189
 - Fix Source issue on Field Report form: https://github.com/IFRCGo/go-frontend/issues/987
 - Link URLs in field report submission: https://github.com/IFRCGo/go-frontend/issues/1108
 - Clear Districts dropdown when Country dropdown is cleared in Field Report form: https://github.com/IFRCGo/go-frontend/commit/bff2f16ce6c5ef7c4b08bc8a9536d95e75ffb2e7
 - Prefetch data and add an initial loading screen: https://github.com/IFRCGo/go-frontend/issues/1386
 - Move all geospatial strings to come from API: https://github.com/IFRCGo/go-frontend/issues/1534
 - Implement translations of all static strings on frontend: https://github.com/IFRCGo/go-frontend/issues/1238
 - Create UI to manage translations: https://github.com/IFRCGo/go-frontend/issues/1240
 - Fix visibility of field reports for IFRC admins: https://github.com/IFRCGo/go-frontend/issues/1501
 - Implement local cache for initial data loads: https://github.com/IFRCGo/go-frontend/issues/1517

### Backend

 - Remove old EPI fields from backend - https://github.com/IFRCGo/go-frontend/issues/1161
 - Add Rich Text Editor support to Admin fields - https://github.com/IFRCGo/go-api/issues/670
 - Fix encoding issue with Rich Text Editor fields - https://github.com/IFRCGo/go-api/issues/837
 - Implement end-points for Tableau Web Data Connector - https://github.com/IFRCGo/go-api/issues/743
 - Management command to import geo-data from shape-field - https://github.com/IFRCGo/go-frontend/issues/938
 - Addition of centroid and bbox fields to geospatial elements in the API - https://github.com/IFRCGo/go-frontend/issues/938
 - Translation of static strings in the backend - https://github.com/IFRCGo/go-api/issues/774
 - Translations for all model text fields in the backend - https://github.com/IFRCGo/go-api/issues/719
 - Setup `Celery` to handle async translation job-flows - https://github.com/IFRCGo/go-api/issues/819
 - Add `is_ifrc_admin` boolean to users end-point in the API - https://github.com/IFRCGo/go-api/pull/845
 - Refactor views to use APIViews - https://github.com/IFRCGo/go-api/pull/840
 - Implement resending verification email - https://github.com/IFRCGo/go-api/issues/737
 - Fix Azure Storage class to help tests + local development - https://github.com/IFRCGo/go-api/issues/825
 - Change FDRS auth to use API key - https://github.com/IFRCGo/go-api/issues/851
 - Add labels to Region model in the backend - https://github.com/IFRCGo/go-api/pull/858
 - Change ElasticSearch configuration settings to improve stability - https://github.com/IFRCGo/go-frontend/issues/1353
 - Fix PDF scraper errors and added more information about errors to logs - https://github.com/IFRCGo/go-api/issues/863
 - Fix ingest_databank error - https://github.com/IFRCGo/go-api/pull/856
 - Removed child Emergencies from appearing in dropdowns - https://github.com/IFRCGo/go-frontend/issues/1487
 - Added 'Activate users' action and 'User is active' column to Pending Users page - https://github.com/IFRCGo/go-api/issues/766
 - Simplify CSV export on Emergencies end-point - https://github.com/IFRCGo/go-api/issues/708

## Deploy Check-list

 - [x] Merge and deploy backend
 - [x] Run `update_translation_fields` management command 
 - [x] Copy Countries, Actions, etc. Translation CSVs to production VM
 - [x] Run `import-translated-strings <filename>` command for each translation CSV.
 - [x] Run all the steps to update geospatial data: https://github.com/IFRCGo/go-frontend/issues/1534#issuecomment-691927120 - @geohacker @jhenshall  can you please review, make sure this is up-to-date, and all linked files are correct. Also, @geohacker @jhenshall to confirm availability to be around whenever we decide to release.
 - [x] Merge frontend
 - [ ] Smoke-test production frontend deploy
 - [ ] Merge frontend master back to develop

### CODE REVIEW

**Comment by thenav56** [comment]
@batpad The command is `python manage.py update_translation_fields`

Also for the celery, right now it's not used anymore (since we are not using automatic translation).

So this should be enough.

**Comment by batpad** [comment]
@thenav56 just confirming - for the celery stuff, would we need to make any changes in config now that we are not using it?

**Comment by GregoryHorvath** [comment]
@batpad to the checklist:
- Copy Countries, Actions, etc translation CSVs to API VM
- Run `import-translated-strings <filename>` command

**Comment by batpad** [comment]
> @batpad to the checklist:

Thanks @GregoryHorvath, added.

**Comment by thenav56** [comment]
> @thenav56 just confirming - for the celery stuff, would we need to make any changes in config now that we are not using it?

@batpad 
Configs should be fine, Similar to the staging.
But I think we should remove the celery task triggers.

Something like this on server.
cc: @GregoryHorvath 
```diff
diff --git a/lang/serializers.py b/lang/serializers.py
index 03ee95e..e0923ec 100644
--- a/lang/serializers.py
+++ b/lang/serializers.py
@@ -100,6 +100,8 @@ class TranslatedModelSerializerMixin(serializers.ModelSerializer):
 
     @classmethod
     def trigger_field_translation(cls, instance):
+        # NOTE: Skip triggering translation
+        return
         if not settings.TESTING:
             transaction.on_commit(
                 lambda: translate_model_fields.delay(get_model_name(type(instance)), instance.pk)
@@ -112,6 +114,8 @@ class TranslatedModelSerializerMixin(serializers.ModelSerializer):
 
     @classmethod
     def trigger_field_translation_in_bulk(cls, model, instances):
+        # NOTE: Skip triggering translation
+        return
         pks = [instance.pk for instance in instances]
         if not settings.TESTING:
             transaction.on_commit(
diff --git a/main/settings.py b/main/settings.py
index e5700b9..00e05d2 100644
--- a/main/settings.py
+++ b/main/settings.py
@@ -323,13 +323,13 @@ CELERY_RESULT_BACKEND = CELERY_REDIS_URL
 CELERY_TIMEZONE = TIME_ZONE
 CELERY_ACKS_LATE = True
 
-CELERY_BEAT_SCHEDULE = {
-    'translate_remaining_models_fields': {
-        'task': 'lang.tasks.translate_remaining_models_fields',
-        # Every 6 hour
-        'schedule': crontab(minute=0, hour="*/6"),
-    },
-}
+# CELERY_BEAT_SCHEDULE = {
+#     'translate_remaining_models_fields': {
+#         'task': 'lang.tasks.translate_remaining_models_fields',
+#         # Every 6 hour
+#         'schedule': crontab(minute=0, hour="*/6"),
+#     },
+# }
 
 RETRY_STRATEGY = Retry(
     total=3,
```

**Comment by batpad** [comment]
@GregoryHorvath would you be able to merge and deploy the above patch to staging so we can test that it does not break anything?

**Review by GregoryHorvath — APPROVED** [review]

**Pull request merged**
