### PR TITLE
Show no data message on Preparedness tab

### PR DESCRIPTION
**Pull request by GergiH**
cc @batpad

### CODE REVIEW

**Review by batpad — APPROVED** [review]

**Comment by batpad** [comment]
This seems like something we would want -- I'm going to keep this PR open, let's merge it after this release and figure out a good way to test. cc @frozenhelium

**Comment by GergiH** [comment]
@batpad This was most probably just a "hotfix" kind of change for the Preparedness tab for the Country pages, connected to the PER rework. But all in all we planned to rework this whole tab too, it just hadn't yet happened.

**Comment by frozenhelium** [comment]
@batpad I've rebased it with latest develop, should we merge this?

**Comment by batpad** [comment]
Thanks @frozenhelium

**Pull request merged**
