### PR TITLE
Not allowing type filtering in RRP table

### PR DESCRIPTION
**Pull request by szabozoltan69**
Solves https://github.com/IFRCGo/go-frontend/issues/1965#issuecomment-912888790 "white page" issue and https://github.com/IFRCGo/go-frontend/issues/2035

### CODE REVIEW

**Comment by szabozoltan69** [comment]
I've put to comment all the not used translations.

**Comment by batpad** [comment]
@szabozoltan69 we will also need to remove the Type arrow dropdown from the header here: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/connected/personnel-table.js#L184 (just make it a simple string and not a FilterHeader)

And also we need to do the same thing for the `all personnel` table, like here: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/connected/personnel-table.js#L184

**Comment by batpad** [comment]
@szabozoltan69 could you also implement the same on the similar, but different `all-personnels` table: https://github.com/IFRCGo/go-frontend/blob/develop/src/root/components/connected/all-personnel-table.js#L145 (Sorry, I see I had the wrong link in my comment above!)

**Comment by szabozoltan69** [comment]
Done for all personnel also.
kép

**Review by batpad — APPROVED** [review]

**Comment by batpad** [comment]
Looks good to me, thanks @szabozoltan69 - once it's on staging, can ask folks to test and verify.

**Comment by szabozoltan69** [comment]
@batpad – It's on staging.
kép

**Comment by szabozoltan69** [comment]
kép

**Pull request merged**
