### PR TITLE
decouples the budget calculations from Appeals

### PR DESCRIPTION
**Pull request by necoline**
#915 
The funding calculations were applied specifically to Appeals and not to DREFs. I am unclear as to whether this was due a miscommunication during ticketing phase [here](https://github.com/IFRCGo/go-frontend/issues/847) or simply a code error.

This change moves the funding calculation to be applied to each object in the reduce rather than just the appeals.

**Note:**  The original logic for this component was copied from the region key figures. This change is applied to countries only and does not adjust the way the DREF and Appeals funding is calculated on the region page.

image

### CODE REVIEW

**Comment by GregoryHorvath** [comment]
@necoline Before I'd merge this, please confirm that this covers what Natalie mentioned in her comment here: https://github.com/IFRCGo/go-frontend/issues/915#issuecomment-603296107. That business logic seems a bit more complicated than what we currently have, but I've just ran through it quickly so I could be wrong.

**Comment by batpad** [comment]
Could we put this up on a testing URL and ask @nanometrenat to confirm the calculation logic? @necoline

**Comment by nanometrenat** [comment]
@mmusori is the man for the calcs.  Sorry I have no bandwidth for this kind of testing right now... Thanks loads for sorting!

**Comment by necoline** [comment]
@batpad before we move onto testing, I want to make sure that we are clear on the desired behavior for this calculation 
> the business logic is not that Appeals and DREFS should be treated separately - in actual fact if there is an Appeal it can often require the DREF to be repaid. So if there is just a DREF then it needs to be the % of that that is calculated, but if there is an appeal as well then the calculations are different (depending on whether the funding amount is sufficient to repay the DREF)

there are still a few open questions on #915 that I would like to see addressed before we move forward with anything

**Comment by batpad** [comment]
We may still have issues to tackle here, but this is being handled separately. Closing this as stale.

**Pull request closed without merging**
