### PR TITLE
Add "Deployments over the last year" chart to the Surge page

### PR DESCRIPTION
**Pull request by willemarcel**
- Create separate component TimeLineChart and use it both on deployments and in emergencies page

PR deployed at https://ifrc-go-new-deploy-chart.surge.sh

### CODE REVIEW

**Comment by frozenhelium** [comment]
@willemarcel We already have `useRequest` hook for fetching data. 
Example: https://github.com/IFRCGo/go-frontend/blob/32407f71c95318bb998cf30523ea4da9af88006b/src/root/components/ThreeWForm/useThreeWOptions.ts#L174-L180
CC: @batpad

**Comment by batpad** [comment]
Thanks so much for the catch and review @frozenhelium -

@willemarcel does this make sense and would you be able to make this change?

**Comment by willemarcel** [comment]
@batpad @frozenhelium I've made the change in order to use `useRequest`.

**Review by batpad — APPROVED** [review]

**Comment by batpad** [comment]
This looks good to me and works well.

@frozenhelium could you take a final look? Thanks.

**Pull request merged**
