### PR TITLE
Implement changes for Early Warning Field Report

### PR DESCRIPTION
**Pull request by batpad**
Refs #833 

Implements all conditionalities and changes required for the Early Warning Field Report.

Additionally, re-organizes how Actions are rendered - now rendering from data supplied by the back-end instead of hard-coded values on the frontend.

cc @necoline

### CODE REVIEW

**Comment by batpad** [comment]
@necoline I've implemented all the changes except for the changes with the Action checkboxes, which is a bit of a larger restructuring.

I'll start working on that now, but if you could give this a look and let me know any feedback on approach, etc., would be great.

**Comment by batpad** [comment]
@necoline this should be fully ready for testing and review.

**Comment by necoline** [comment]
I think you have done a great job with this. It's great to see this code get cleaner with these additions. 👏 

There were a few things that I noticed:
- Step 2 is set up for only number inputs so the validation misses the text input for `affectedPopCentres` which should be a string
- this is a preexisting bug, but the check-box `Damage/Needs assessment`throws this error when checked: `TypeError: Cannot set property 'checked' of undefined` )  ... I don't know if this is something to add to this PR, but I wanted to make note of this so we can return to it later
- Upon completion, I cannot go back and edit the form: 
image

It looks like there is an error with the value being passed int `sourceEstimationMapping` in the utils

Just minor things aside from the edit button. Overall, really well done!

**Comment by batpad** [comment]
Things TODO to complete this PR:

 - [x] Fix stepper titles according to form status
 - [ ] Fix validation for `Affected Pop Centres` field (needs to be a string)
 - [ ] Fix loading of hard-coded actions in `getInitialState` to use actions sent from the API
 - [ ] Fix `convertFieldReportToState` to correctly load field report for editing with new fields, etc.

There are two additional items todo to complete the Field Report Early Warning:

 - Add Yes / No field for `National Society Requires International Assistance` (similar to `Government Requires International Assistance` to appear right below) - this field appears on both EVT and EW forms.
 - Add a field for `other_sources` as a text field in Step 2, for the user to specify text for sources where they have mentioned `Other` as the source above.

I will create a separate ticket for these two additional fields ^ and do these in a separate PR.

**Comment by batpad** [comment]
> Fix validation for Affected Pop Centres field (needs to be a string)

@necoline this is already defined as a string in the validation schema definitions. The validator does pass an all-numeric input as a "string". I do think that changing that is a bit more work and is not how string validation works in other places, so I'm inclined to leave this as is.

I think I've fixed all the other issues with loading the form, and the problem with some checkboxes. Loading of the Field Report depends on this backend PR being merged: https://github.com/IFRCGo/go-api/pull/555

**Comment by batpad** [comment]
I believe this is ready to be tested. I have created a separate ticket for the additional two fields to be added: https://github.com/IFRCGo/go-frontend/issues/880

I'm going to squash commits here so we have a single commit for this.

**Pull request merged**
