### PR TITLE
Release v4.6

### PR DESCRIPTION
**Pull request by GregoryHorvath**
#### Changes

- Added `sovereign_state` and `disputed` fields to Countries - https://github.com/IFRCGo/go-api/commit/2ab667c741d504f27d83cf4eba68e2ba765c0358#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
- Added management scripts for the Country and District tilesets - https://github.com/IFRCGo/go-frontend/issues/1474
- Allow users to log-in with their `email` too besides `username` - https://github.com/IFRCGo/go-frontend/issues/1663
- New API endpoint introduced `/api/v2/appeals_aggregated/` mainly for FDRS to use, which returns the data used for our key-figures in the headers. The possible filters are `iso3` (country-iso3), `country` (country-id), `region` (region-id)
- Added new Appeal type: FBA / EAP - https://github.com/IFRCGo/go-frontend/issues/1798
- Multiple COVID Field Report changes / additions (text changes, added tooltips, new fields, etc) - https://github.com/IFRCGo/go-frontend/issues/1797
- Made ElasticSearch to handle Country changes, and added a new boolean field called `in_search` (for Admins to set) which determines if the actual Country should show up in the search or not - https://github.com/IFRCGo/go-frontend/issues/1673#issuecomment-749554798, https://github.com/IFRCGo/go-frontend/issues/1643#issuecomment-774510978
- Now Admins can edit contacts shown on the Resources page through the Django Admin - Main contacts - https://github.com/IFRCGo/go-frontend/issues/1820
- Fixed API endpoints' route mapping on their main page `/api/v2/` and now they should show up in alphabetical order - https://github.com/IFRCGo/go-api/issues/1004
- Fixed typo in the footer - https://github.com/IFRCGo/go-frontend/issues/1809
- Fixed global key-figures header showing for Africa's region page - https://github.com/IFRCGo/go-api/issues/1008
- Fix for Field Report counts - https://github.com/IFRCGo/go-frontend/issues/1504

#### TODOs

- [x] disable the Molnix cronjob
- [x] increase version in the deployment
- [x] deploy backend
- [x] run `./manage.py add_partner_dropdownitems`
- [x] run `./manage.py add_main_contacts`
- [ ] run `./manage.py add_action_tooltips`
- [ ] run `./manage.py update_translation_fields`
- [ ] run `./manage.py set_in_search_init`
- [ ] run `./manage.py index_elasticsearch`
- [ ] deploy frontend
- [ ] re-enable the Molnix cronjob for staging

### CODE REVIEW

**Comment by GregoryHorvath** [comment]
@batpad @geohacker @kamicut Please look through the changes and TODOs and edit if needed, I feel like I definitely missed some stuff.

**Comment by geohacker** [comment]
@GregoryHorvath this looks good to me. The only thing to note is that `./manage.py update-sovereign-and-disputed new_fields.csv` should NOT be run on production. cc @batpad

**Comment by GregoryHorvath** [comment]
> @GregoryHorvath this looks good to me. The only thing to note is that `./manage.py update-sovereign-and-disputed new_fields.csv` should NOT be run on production. cc @batpad

Removed them from the TODOs.

**Comment by batpad** [comment]
> Should we disable Molnix cronjob? Its interval was changed from 15 to 5 minutes, should we keep this?

Sorry for the late reply @GregoryHorvath - yes, we would need to disable this for the prod deploy.

Keeping it at 5 for now is fine, we can check with the team what it needs to be when we go live.

**Comment by batpad** [comment]
@GregoryHorvath sorry, one thing to add to release notes - fix for Field Report Counts - https://github.com/IFRCGo/go-frontend/issues/1504

**Review by batpad — APPROVED** [review]

**Pull request merged**
