### PR TITLE
Don't cut the map at 180

### PR DESCRIPTION
**Pull request by geohacker**
Fixes https://github.com/IFRCGo/go-frontend/issues/1629

cc @batpad  @jhenshall

### CODE REVIEW

**Comment by geohacker** [comment]
@jhenshall if you'd like to test this https://ifrc-go-fix-map-at-180.surge.sh/

**Comment by jhenshall** [comment]
Whoa @geohacker , so quick!! This is awesome. Seems good to go as a fix for the majority of the issue. Intrigued how regions and countries that split the 180 line can be handled in the backed?

**Comment by geohacker** [comment]
>  Intrigued how regions and countries that split the 180 line can be handled in the backed?

Yeah this needs a bit more thinking but definitely doable :)

**Review by batpad — APPROVED** [review]

**Comment by batpad** [comment]
Merging this as this fix definitely seems like an improvement? cc @geohacker @jhenshall

**Pull request merged**
