### PR TITLE
Feature/1004 epi field report

### PR DESCRIPTION
**Pull request by necoline**
#1004
The PR includes:
- disable early warning on epidemic disaster
- new fields for estimation source organizations
- epidemic specific situation fields
- date of data
- required start date
- validation for new fields 
- sections for action checkboxes on EPI (or any future form type that has multiple categories)
- larger text boxes

Known pre-existing issues:
- Minor form validation issues: fields accepting numbers do not check if number is an integer
- Does not reset the province field when the country is changed. 
- Does not allow ‘yes/no’ questions to be submitted as empty (will automatically choose ‘no’ if none is selected
- Does not add tool tip or other feature to explain abbreviations
- Does not automatically set title
	
Known EPI shortcomings:
- Does not include file upload (only text url) — recommended future work
- Does not update date of data on edit — will look into this

url to test: https://ifrc-go-feature-1004-epi-field-report.surge.sh/

### CODE REVIEW

**Comment by necoline** [comment]
I updated the validations. I'm not sure if all of the values will match up, but the payload reflects the epi-specific values

image

**Comment by karitotp** [comment]
**To test:**

✅ The form fields exist

❌ Form matches design

   - Not all forms math with the design, left a comment of that [here](https://github.com/IFRCGo/go-frontend/issues/1004#issuecomment-610067732) 

❌ Form entry validation works
   - Number fields does not allow other characters or letters  ✅ 
   - Number fields must allow only integer numbers ❌ 

estimation

✅  Changes do not cause side effects for other types of forms

**Comment by batpad** [comment]
@necoline this is looking great! :tada: 

@karitotp things that should now work:

 - Actions should all show up in step 3.
 - Saving the form and seeing all the information on the Field Report page after you save should work.
 - When clicking Edit to edit the form, all the data that was saved should load up correctly in the Edit mode, and allow you to edit and re-save, and that should save correctly.

@karitotp will be great if you can make separate notes for:

 - Anything where data is not being saved or loaded correctly.
 - Issues with the styling and text

Thank you! This is looking really close to me.

**Comment by karitotp** [comment]
@batpad, the things are working good!! just a minor issue in one field :point_down:, about the styling and texts, is the same that I commented before.

- [x] Actions should all show up in step 3.
- [x] Saving the form and seeing all the information on the Field Report page after you save should work.
- [x] When clicking Edit to edit the form, all the data that was saved should load up correctly in the 
  Edit mode, and allow you to edit and re-save, and that should save correctly.

  In this step all the saved data is loading in edit mode and all is re-saved correctly a exception of the 
  `Data of Date*` data. 

date

   I tested this in two scenarios. 

   - **Editing a just created report (report id: 9515)**
     The field is not loading any data. I input a date, I save the edition, but when I open again 
     the edit mode of the report, the field is empty again.

   - **Editing a previous created report (report id: 9512)**
     The field is loading the saved date, but when I change this date, this is not being saved. When I 
      open again the edit mode the field is loading the initially saved date.

**Comment by necoline** [comment]
The above commit fixes:

> When clicking Edit to edit the form, all the data that was saved should load up correctly in the
Edit mode, and allow you to edit and re-save, and that should save correctly.

**Pull request merged**
