### PR TITLE
Added RDRT into RR for Deployments stats

### PR DESCRIPTION
**Pull request by GregoryHorvath**
@batpad There could be a more sophisticated way to do login in `.scss` files for these kind of stuff. I basically just copied the `.stats-list` section as a whole and changed `@include column(4/12);` to have only 3 columns (since `.stats-list` is used by the Emergencies page too).

**Feel free to change/fix or comment your thoughts please before merging this.**

### CODE REVIEW

**Comment by batpad** [comment]
As per our new frontend testing workflow, I have created a temporary URL to test this change here: https://ifrc-go-fix-deployed-rr.surge.sh

@teklal if you're able to verify this change works on the above URL and fixes #965, we can go ahead and merge to develop.

@GregoryHorvath Could you leave a comment on the CSS with maybe a note, but it looks *okay* to me - but I'm also not a CSS expert. If it works with @teklal testing, let's merge this.

Let me know and I'll make sure to teardown the URL on surge once this is tested.

**Comment by batpad** [comment]
@GregoryHorvath just fyi: I also merged in newer changes from develop into this branch

**Comment by batpad** [comment]
> As per our new frontend testing workflow, I have created a temporary URL to test this change here: https://ifrc-go-fix-deployed-rr.surge.sh

Oops, teething troubles with this testing flow - doesn't seem to be getting data, will fix and update here.

**Comment by batpad** [comment]
Sorry about that - https://ifrc-go-fix-deployed-rr.surge.sh/ now works and can be tested. cc @teklal @GregoryHorvath

**Comment by teklal** [comment]
Wow, having that separate URL is great! Tested the fixes and they work, so good to merge from my end.

**Pull request merged**
