### PR TITLE
#1669: Minor UI enhancements to PER Forms

### PR DESCRIPTION
**Pull request by imohkay**
Minor UI changes including:
- Accurate positioning of save button
- Same width for Edit, View and Delete buttons in form list
- Button sizes for modal box and Start a New Assessment button

### CODE REVIEW

**Comment by batpad** [comment]
@GregoryHorvath could you please review / merge if it looks good to you?

**Review by GregoryHorvath — APPROVED** [review]

**Comment by GregoryHorvath** [comment]
@imohkay @batpad I'm seeing a conflict there `_typography.scss`, could you please resolve that so we can merge?

**Comment by imohkay** [comment]
@GregoryHorvath @batpad I've resolved the conflict.

**Comment by batpad** [comment]
@GregoryHorvath please merge if all looks good, thanks!

**Pull request merged**
