### PR TITLE
Handle empty language values

### PR DESCRIPTION
**Pull request by frozenhelium**
Filter out empty language string before sending to server

### CODE REVIEW

**Comment by szabozoltan69** [comment]
@frozenhelium @batpad what would be the best practice to put this change as a hotfix to prod also?
(Daniel asked me to put it to prod also, but the whole develop branch can not go to prod, just this fix.)
The aim is: at next develop->prod merge we do not want to find it as a conflict.

**Comment by frozenhelium** [comment]
@szabozoltan69 we can create a new branch from master and cherrypick this commit and create new pr to master

**Comment by szabozoltan69** [comment]
I've never done cherrypick. Maybe it would be good if this were not my first trial... :-)
Could you please prepare it? (Even the command themselves would be great.)

**Comment by frozenhelium** [comment]
@szabozoltan69 here's the steps
- Go to the `develop` branch
- Copy the hash for the required commit, which is `c7ac0fba41e670769f32203a5e3e1df0676a53e9` in this case,
- Go to the `master` branch, and make sure you have the latest changes in your local machine
- Now, create a new branch for hot-fix
- Do `git cherrypick c7ac0fba41e670769f32203a5e3e1df0676a53e9`
- Push the branch and create the PR

Please, let me know if you run into some trouble

**Comment by szabozoltan69** [comment]
@frozenhelium Succeeded fine, thanks for the brilliant guidelines!

**Pull request merged**
