### PR TITLE
map date filter

### PR DESCRIPTION
**Pull request by necoline**
#828 

This still needs a lot of work 
- styling
- removing duplicate time-date-header components

### CODE REVIEW

**Comment by batpad** [comment]
@necoline this is looking really good to me. I can also confirm that the functionality seems to work well.

I do imagine the styling will be a little bit of a challenge - a bit curious to see how you are going to approach that :-)

After the date filter for the map is implemented, we can probably ticket out where things stand with the filters and why some are implemented differently and what longer term plans for the filters are, from a user / UI perspective as well as a code / refactoring perspective (more on this in #828 ).

This approach to harmonizing the date filter into a common component looks really solid - I do imagine the styling and little things will be a bunch of work - but I do think it's an approach we can re-use really well. Let me know if I can help or if it helps to talk through any of this.

**Comment by necoline** [comment]
I don't have a clear roadmap for the styling. I am going to put some time into this today. My initial plan is to identify the component specific styles and their class names and dynamically insert the classnames with prop based values. Another approach could be to extract the component specific elements into separate component wrappers around the common date filter... whatever is most readable and reusable as a practice for future refactoring.

**Comment by necoline** [comment]
Okay, so our dropdown component that we are using for dates and selects is a bit of a beast. (see https://github.com/IFRCGo/go-frontend/blob/5d74fd2c0ebe119cf18b00c4b203da99babab2d2/app/assets/scripts/components/dropdown.js#L32 
After spending some time trying to figure out how it worked so I could make modifications to apply it to the map selects, I backed out.

To deal with the styling, I took the first approach mentioned above of applying styles specific to the dates feature type. 

The dropdown has strange behavior that triggers a re-render when filters are submitted, this wasn't working on the map date filter, rather it was stuck in an open state. Neither of theses scenarios is ideal. 

I implemented a brute force method of closing the date filter after submission.

I think this fix is adequate for now. I'm not happy with the variations of selects that we are using across the site and would be more than happy to find a replacement to our dropdown component. While it's widely used across the site, I think we think about making plans to update this to something a bit more wieldy.

**Comment by necoline** [comment]
Adds date filter to maps on home and region pages
## Description
I applied the date filter from the table to the map and made the dropdown styles dynamic to remain consistent with neighboring selects

I did this by extracting the date filter from the `display-table` into a common component accessible to all components making use of it. 

## Related Issue
#828 

## Motivation and Context
The data populating the map and table is the same. While some of the logic needed to implement the tables and map is feature specific, there is data that should be displayed through both mediums. Allowing the users to select date ranges for the map display was part of this process. 
As I made this available, I also tried to make steps to create common components between the map and table so we can work towards offering more common filtering between the components

## How Has This Been Tested?
This has been manually tested in development


## Screenshots (if appropriate):
Home:
image

Region:
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Comment by batpad** [comment]
@necoline the implementation looks good to me and the date filter works well.

>  I think it would worthwhile to discuss a replacement for this dropdown and unification of selects across the site.

It would be great to create a ticket for this - this would be a good conversation to have with @frozenhelium as well and do a general assessment of the state of dropdowns across the site and how we want to standardize.

@necoline small feedback from a user perspective, not sure of the best way to fix:

 - The `hover` styling for the Date drop-down seems a bit inconsistent with the filters next to it (turns grey)
 - The `Date` heading jumps a little bit when clicked on

^ These are probably the result of some default styling for `<a>` elements? These are not a huge deal.

The other thing is I wonder if we need some sort of indication that the Date filter is currently active. For the filters next to, for example, you see the currently searched for item. With the Date filter, currently, there's no obvious way to know if the filter is active or not without clicking on it. This maybe a UX question for later, though.

Overall, this looks good, and structurally sets us up well to make the filters across the table and map consistent as well as make this whole map + table + filters behaviour consistent across the home and region pages.

**Comment by batpad** [comment]
@necoline I left a note about the logic of the date comparator. If we can get that resolved, I don't think any of the other issues should block merging this.

**Pull request merged**
